# Generated by Django 3.2.5 on 2021-07-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210708_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitoblar',
            name='kitob_haqida',
            field=models.TextField(null=True),
        ),
    ]
